NOTIF-152 Adds recipients.users
RedHatInsights/insights-schemas-java pull request #24
Opened 2021-11-22 16:39 UTC by josejulio

2022-01-12 12:35 UTC, bennetelli reviewed
I guess https://github.com/RedHatInsights/insights-schemas-java/blob/04e840668673a40149030a1b138ad950e763391a/insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java#L21 

is testing the new/latest schema version 1.2.0?

2022-01-12 12:42 UTC, bennetelli requested changes

2022-01-12 12:42 UTC, bennetelli commented on insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
> +        Decoder decoder = new Decoder(registry);
Not much important, but these three lines could be moved to a beforeEach method.

2022-01-12 12:42 UTC, bennetelli commented on insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
> +        System.out.println("encoded:" + encoded);
i think this can be removed?

2022-01-12 12:42 UTC, bennetelli commented on insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
> +        Assertions.assertThrows(AvroRuntimeException.class, () -> action.put("version", "v1.0.0"));
all the static Assertions.* could be changed to static imports. Also not that important but improves readability a bit

2022-01-12 13:10 UTC, josejulio commented on insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
> +        System.out.println("encoded:" + encoded);
whoops, yes

2022-01-13 13:58 UTC, josejulio commented
> is testing the new/latest schema version 1.2.0?

yes, it tests using the latest

2022-01-14 12:44 UTC, bennetelli commented on insights-notification-schemas-java/src/test/java/com/redhat/cloud/notifications/ingress/TestSerialization.java
> +        Decoder decoder = new Decoder(registry);
I am not merging it so you can decide if you want to put the creation of these three objects in a before method or not :-)
if not, feel free to merge :)

2022-01-14 14:56 UTC, merged